"""Adding announcement table

Revision ID: 19c5300a4b2f
Revises: 
Create Date: 2021-02-11 10:04:22.557012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c5300a4b2f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(), nullable=True),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('publisher', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('project_code', 'version', name='project_code_version'),
    schema='indoc_vre'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('announcement', schema='indoc_vre')
    # ### end Alembic commands ###
