apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: utility
  labels:
    app: notification
    env: charite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
      env: charite
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: notification
        env: charite
    spec:
      containers:
        - name: notification
          image: 10.32.42.225:5000/notification:<VERSION>
          ports:
            - containerPort: 5065
          env:
          - name: env
            value: "charite"
          - name: RDS_PWD
            valueFrom:
              secretKeyRef:
                name: opsdb
                key: password
          readinessProbe:
            tcpSocket:
              port: 5065
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "1000Mi"
              cpu: "1"
            limits:
              memory: "1000Mi"
              cpu: "1"
      nodeSelector:
        namespace: utility
---
apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: utility
  labels:
    app: notification
    env: charite
spec:
  ports:
  - name: notification
    port: 5065
    targetPort: 5065
  selector:
    app: notification
    env: charite
  type: ClusterIP
